### ISSUE TITLE
Dead links to random number generators

### ISSUE THREAD

**Issue by thomwiggers** [rust-random/book#31]
on the page ["Our RNGs"](https://rust-random.github.io/book/guide-rngs.html) the links to random number generators that are not part of the [rust-random/rand](/rust-random/rand) crate are dead. I think the [rust-random/rngs](/rust-random/rngs/) repository needs a similar github-pages CI workflow.

**Comment by dhardy** [comment]
Would you like to make a PR?

**Comment by dhardy** [comment]
Fixed in #32
