### ISSUE TITLE
Guide page for generating seeded random floats

### ISSUE THREAD

**Issue by Harnesser** [rust-random/book#7]
Hi all,

I'd love to see recipe page on the best way to generate seeded random floats for procedural generation applications.

This request comes from a recent unsuccessful experience I had trying to upgrade from 0.3 to 0.6 of `rand`.  My 0.3 code uses a {`SeedableRng`, `from_seed()`, `next_f32()`} recipe I found on the web somewhere that's not suitable for 0.6, plus a `--seed` command line option to set the seed.

* Do I need to use `from_seed_u64()` now? 
* Do I need to implement a trait on a typedef like in the tests? 
* Do I need to add `rand_core` as well as the usual `rand` to `Cargo.toml`.
* Do I need to decide on a PRNG? Can you suggest a suitable one for procedural generation work?

Thanks!

**Comment by dhardy** [comment]
[Is this what you want](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c80901611798939225cc0dd50e93982a)?

Sorry, I don't quite follow. If you know how to improve the documentation though, a contribution would be very welcome!

To answer your bullet points:

- `SeedableRng::seed_from_u64` is the easiest way to seed from an integer
- Don't know what you mean here; you can't implement traits on typedefs anyway. You do have to "use" (import) traits.
- No; all the bits of `rand_core` (other than utilities for implementing new RNGs) are availble in `rand` too
- Yes, you should decide on a PRNG. Probably any of the ones we have are suitable for procedural generation, crypto or not (the main difference being crypto ones use more memory and batch their generation). If you want reproducible generation across library versions, then don't use `SmallRng` / `StdRng`; you may want to look at the `rand_xoshiro` and `rand_pcg` crates (first one isn't published yet but hopefully will be later today)

**Comment by dhardy** [comment]
It's also worth noting that using `gen_range` or the `Uniform` distribution may be a little faster and more accurate than using `gen()` and modifying/shifting the result. Here's an [expanded example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4fc5137bcd1554e4be4b4254689698f2).

**Comment by Harnesser** [comment]
Thanks - the first example was especially useful!

I would have like to have found a "recipe" page in the docs with:
* the above example
* some of your remarks above
* and maybe notes on re-seeding in an interactive application
* with links to more in-depth section in the rand-book

I'd like to have a go at creating such a page for documentation, as thanks for your help. I'm not sure if the page would be best in the rand book, or in the main Rust Cookbook. What do you think?

Thanks again!

**Comment by dhardy** [comment]
> I'm not sure if the page would be best in the rand book, or in the main Rust Cookbook. What do you think?

Depends where people are more likely to look for such documentation?

The book as it stands was written fairly quickly to at least have some doc beyond the API. It could certainly be expanded significantly. I can't gauge what content all readers want and also don't currently want to contribute new content to the book myself, but if you would like to I would be happy to review.
